spring:
  profiles:
    active: prod

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  server:
    error:
      include-message: always

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}

  jpa:
    hibernate:
      ddl-auto: create-drop

  server:
    error:
      include-message: always